"""empty message

Revision ID: 5874e29c90d3
Revises: 8747ec8a7c01
Create Date: 2022-08-17 15:58:58.926243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5874e29c90d3'
down_revision = '8747ec8a7c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'name')
    op.drop_constraint('venue_artist_id_fkey', 'venue', type_='foreignkey')
    op.drop_column('venue', 'artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('venue_artist_id_fkey', 'venue', 'artist', ['artist_id'], ['id'])
    op.add_column('show', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
