"""empty message

Revision ID: 8747ec8a7c01
Revises: 76744bf2ca34
Create Date: 2022-08-16 13:22:52.655813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8747ec8a7c01'
down_revision = '76744bf2ca34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_show',
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], )
    )
    op.add_column('venue', sa.Column('show_id', sa.Integer(), nullable=False))
    op.add_column('venue', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venue', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'venue', 'show', ['show_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_column('venue', 'artist_id')
    op.drop_column('venue', 'show_id')
    op.drop_table('artist_show')
    op.drop_table('show')
    # ### end Alembic commands ###
